services:
  - type: web
    name: finwise
    runtime: node
    plan: free
    buildCommand: npm install && npm install --prefix server && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://finwise-1-v170.onrender.com
      - key: VITE_API_URL
        value: https://finwise-knz0.onrender.com
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false